Add first Orbit tutorial
kiwicom/orbit-swiftui pull request #193
Opened 2022-06-23 08:29 UTC by PavelHolec

An "hello world" tutorial. Wording is rough, any copy suggestions welcome 🙏 

![image](https://user-images.githubusercontent.com/35844477/175253641-ddcec08f-c876-4ae7-8db5-4a3cc5e45c8e.png)

2022-06-23 09:02 UTC, sjavora requested changes
Nice!

A note about screenshots - I _think_ we should have dark mode versions of them. Also, the "hello world" screen could potentially be made smaller - it's shown over the code sample (and I did not open it - it's done automatically).

<img width="875" alt="Screenshot 2022-06-23 at 11 01 53" src="https://user-images.githubusercontent.com/12349477/175260998-71995630-f8ae-48dc-bc86-9d9710c785df.png">

2022-06-23 10:09 UTC, PavelHolec commented on Sources/Orbit/Orbit.docc/Tutorials/Tutorials.tutorial
> +        These tutorials will help you get familiar with our design system by building a simple login screen, while learning design foundations and components along the way.
Removed for now. Any idea for some additional generic description?

2022-06-23 10:52 UTC, PavelHolec commented
> A note about screenshots - I _think_ we should have dark mode versions of them. Also, the "hello world" screen could potentially be made smaller - it's shown over the code sample (and I did not open it - it's done automatically).

Resized the snapshots 👍 
Added dark variant, but for future tutorials, I am not sure it will be possible - as our components currently support only an experimantal, hacky, Dark Mode.

2022-06-23 10:56 UTC, sjavora commented
True, and the only Xcode screenshots will probably be in this tutorial...

2022-06-23 12:27 UTC, sjavora commented on Sources/Orbit/Orbit.docc/Tutorials/01-01-hello_orbit.tutorial
> +                @Image(source: 01-01-hello_orbit-s01, alt: "TBD")
```suggestion
                @Image(source: 01-01-hello_orbit-s01, alt: "A screenshot showing the App template selected in Xcode's project template picker")
```

2022-06-23 12:27 UTC, sjavora commented on Sources/Orbit/Orbit.docc/Tutorials/01-01-hello_orbit.tutorial
> +                @Image(source: 01-01-hello_orbit-s02, alt: "TBD")
```suggestion
                @Image(source: 01-01-hello_orbit-s02, alt: "A screenshot of Xcode showing an open project with the Package Dependencies tab open, highlighting the plus button")
```

2022-06-23 12:27 UTC, sjavora commented on Sources/Orbit/Orbit.docc/Tutorials/01-01-hello_orbit.tutorial
> +                @Image(source: 01-01-hello_orbit-s03, alt: "TBD")
```suggestion
                @Image(source: 01-01-hello_orbit-s03, alt: "A screenshot of Xcode showing the package search UI with orbit-swiftui shown in search results")
```

2022-06-23 12:27 UTC, sjavora commented on Sources/Orbit/Orbit.docc/Tutorials/01-01-hello_orbit.tutorial
> +                @Image(source: 01-01-hello_orbit-s04, alt: "TBD")
```suggestion
                @Image(source: 01-01-hello_orbit-s04, alt: "A screenshot of Xcode showing the package product selection pop-up with Orbit checked")
```

2022-06-23 12:28 UTC, sjavora commented on Sources/Orbit/Orbit.docc/Tutorials/Tutorials.tutorial
> +        These tutorials will help you get familiar with our design system by building a simple login screen, while learning design foundations and components along the way.
Not really...

2022-06-24 07:34 UTC, sjavora approved these changes

2022-06-24 08:03 UTC, merged