Remove vertical fixed size of EmptyState button
kiwicom/orbit-swiftui pull request #273
Opened 2022-08-16 10:44 UTC by PavelHolec

2022-08-19 08:17 UTC, Parabak approved these changes

2022-08-29 10:41 UTC, PavelHolec commented
@sjavora @Parabak please recheck - the only solution I found to address the issue is to add a new modifier (see issue description)

2022-08-29 11:21 UTC, sjavora requested changes

2022-08-29 11:21 UTC, sjavora commented on Sources/Orbit/Components/Button.swift
> +//            storybookMix
Commented code.

2022-08-29 11:21 UTC, sjavora commented on Sources/Orbit/Components/Button.swift
> +//}
More commented code.

2022-08-29 11:43 UTC, PavelHolec commented on Sources/Orbit/Components/Button.swift
> +//}
Thx, updated both

2022-08-29 12:36 UTC, sjavora approved these changes

2022-08-29 13:05 UTC, merged